spring:
  application:
    name: customer
  profiles:
    active: production
info:
  app:
    name: "Customer"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
application:
  allow-get-accounts: ${accounts.allow-get-accounts}
#eureka:
#  client:
#    ${eureka-client}
server:
  port:
    8884
feign:
  circuitbreaker:
    enabled: true